[package]
name = "rt-evm-mempool"
version = "0.1.0"
edition = "2021"

[dependencies]
ruc = "4.1"
moka = "0.10.0"
crossbeam-queue = "0.3.8"
parking_lot = "0.12.1"

rt-evm-model = { path = "../model" }
